
list = {
    100 : "message : be a strong man, take your adventurous life, make your dream come true, have a great career, live the wonderful life befor you become dust and sand",
    0 : "egg",
    1 : "iron nail",
    2 : "pivate's hand",
    3 : "lips",
    4 : "chair",
    5 : "hand",
    6 : "lock",
    7 : "hammer",
    8 : "poly-roly",
    9 : "flag",
    10 : "messi",
    11 : "chopsticks",
    12 : "harp",
    13 : "black",
    14 : "petronas twin tower",
    15 : "$",
    16 : "teapot",
    17 : "triangle ruler",
    18 : "18+ sexy girl",
    19 : "safety pin",
    20 : "snail",
    21 : "beer cup",
    22 : "caliper",
    23 : "duck",
    24 : "mantis",
    25 : "scale",
    26 : "X = twitter",
    27 : "clothes hanger",
    28 : "bicycle",
    29 : "cao cát",
    30 : "spider",
    31 : "toothbrush",
    32 : "hiiu",
    33 : "flock of storks",
    34 : "buffalo",
    35 : "scissor",
    36 : "elephant",
    37 : "chư bát giới trident rake",
    38 : "crab",
    39 : "scorpion",
    40 : "small truck",
    41 : "boat",
    42 : "hen's head",
    43 : "pig",
    44 : "camel",
    45 : "chiến thắng Điện biên phủ", #new
    46 : "squirrel", #new
    47 : "mouse",
    48 : "lion's head", #
    49 : "chameleon",
    50 : "rapper 50cent", 
    51 : "si",
    52 : "heart",
    53 : "jellyfish",
    54 : "vn",
    55 : "river",
    56 : "spray bottle", #
    57 : "fan",
    58 : "majin buu = fat buu",
    59 : "swim",# ?
    60 : "headphone",
    61 : "shovel",
    62 : "kowtow = bow down",
    63 : "key",
    64 : "copper",
    65 : "apple",
    66 : "eyes",
    67 : "shrimp = pen",
    68 : "tank",
    69 : "bagua",
    70 : "golf stick",
    71 : "sniper gun",
    72 : "n",
    73 : "bitcoin",
    74 : "A",
    75 : "dinh độc lập 1975",
    76 : "bún spoon",
    77 : "Ak gun",
    78 : "guita = ant",
    79 : "dog sit",
    80 : "monkey's face",
    81 : "skateboard",
    82 : "motorbike",
    83 : "butterfly",
    84 : "tree",
    85 : "bow tie",
    86 : "công nông",
    87 : "pinwheel",
    88 : "bugatti",
    89 : "helicopter",
    90 : "turtle",
    91 : "grasshopper",
    92 : "baby",
    93 : "bee",
    94 : "dung beetle",
    95 : "start",
    96 : "%",
    97 : "rainbow",
    98 : "moon",
    99 : "sun"
}
import random
# n = 0
# for i in range(101) :
#     # print(i," : ",list[i])
#     if list[i] == "" :
#         n += 1
#         print(n," : ", i)
# if n == 0 :
#     print("done full number !!")

for i in range(100) :
    a = random.randrange(0,99)
    print(a, end= '')    
